#!/usr/bin/env python3
"""Build the six "What the app does" card animations from one source.

    python3 tools/build-cards.py

concepts/cards/template.html is the source: the scene markup, styles and
timelines, with two placeholders that this script fills from public/index.html
so the drawings can never drift from the hero animation:

    /*ICON*/       the hero's produce drawings (the ICON object)
    <!--BASKET-->  the hero's woven basket (its two SVG layers)

It writes two things:

  1. concepts/cards/index.html: the standalone prototype, for review.
  2. public/index.html, between marker comments, with every class prefixed
     `cs-` and the basket's SVG ids renamed, so nothing collides with the
     hero's own classes and ids on the same page:
        <!-- cards:scenes … -->   one scene div per card, before its <h3>
        /* cards:css … */          the scene styles, inside the page's <style>
        /* cards:js … */           the timelines, inside the hero's script

Run it after any change to the template, and commit both outputs.
"""
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
tpl = (root / 'concepts/cards/template.html').read_text()
home_path = root / 'public/index.html'
home = home_path.read_text()

# ---- the hero's drawings -------------------------------------------------
a = home.index('const ICON = {'); b = home.index('};', a) + 2
icon_js = home[a:b]
i = home.index('<div class="basket" id="basket">'); j = home.index('<span class="plus" id="plus">', i)
layers = re.findall(r'<svg class="layer"[\s\S]*?</svg>', home[i:j])
assert len(layers) == 2, len(layers)
basket = '\n'.join(re.sub(r'\n\s*', '\n', l) for l in layers)

# ---- 1. the prototype ----------------------------------------------------
proto = tpl.replace('/*ICON*/', icon_js).replace('<!--BASKET-->', basket)
(root / 'concepts/cards/index.html').write_text(proto)

# ---- 2. the homepage -----------------------------------------------------
# The scene styles: from `.fit {` to the no-JS rule, every class prefixed.
css = tpl[tpl.index('.fit { position: relative;'):tpl.index('html:not(.js) .fit')]
css = re.sub(r'\.(?![0-9])([a-z][a-z-]*)', r'.cs-\1', css)
css = css.replace('.cs-fit { position: relative; width: 100%;', '.cs-fit { position: relative; width: 100%; margin: 0 0 16px;')
css = '  /* cards:css start (generated by tools/build-cards.py from concepts/cards/template.html; do not edit here) */\n' + \
      '\n'.join('  ' + l if l.strip() else l for l in css.rstrip().split('\n')) + \
      '\n  html:not(.js) .cs-fit { display:none; }\n  /* cards:css end */\n'

# The six scenes: each `.fit` block, classes prefixed, basket ids renamed.
scenes = re.findall(r'      <div class="fit">[\s\S]*?</div></div>\n', tpl)
assert len(scenes) == 6, len(scenes)
def prefix_classes(html):
    return re.sub(r'class="([^"]*)"', lambda m: 'class="' + ' '.join('cs-' + c for c in m.group(1).split()) + '"', html)
basket_page = basket.replace('fb-body', 'cs-body').replace('fb-round', 'cs-round').replace('fb-down', 'cs-down')
basket_page = basket_page.replace('<svg class="layer"', '<svg')
scenes = [prefix_classes(s).replace('<!--BASKET-->', basket_page) for s in scenes]

# The timelines: from the EXTRA drawings to the last scene, class selectors prefixed.
js = tpl[tpl.index('const EXTRA = {'):tpl.rindex('})();')]
js = js.replace("$('.phone')", "$('.cs-phone')").replace("$('.paper')", "$('.cs-paper')")
js = js.replace("function fit() { document.querySelectorAll('.fit')", "function fitCards() { document.querySelectorAll('.cs-fit')")
js = js.replace("fit(); addEventListener('resize', fit);", "fitCards(); addEventListener('resize', fitCards);")
js = js.replace('const tick = (A, t, sel)', 'const landTick = (A, t, sel)').replace('tick(A, ', 'landTick(A, ')
js = js.replace('const RM = ', 'const RM_ = ')   # the hero's IIFE already has RM and E
assert "const E = " not in js
js = '/* cards:js start (generated by tools/build-cards.py from concepts/cards/template.html; do not edit here) */\n' + js.rstrip() + '\n/* cards:js end */\n'

def replace_between(text, start, end, new):
    """Replace from the line holding `start` to the line holding `end`, or insert `new` at `at` when absent."""
    if start in text:
        a = text.rindex('\n', 0, text.index(start)) + 1
        b = text.index('\n', text.index(end)) + 1
        return text[:a] + new + text[b:]
    return None

out = replace_between(home, '/* cards:css start', '/* cards:css end */', css)
if out is None:
    k = home.index('  .band:not(.band-alt) .cell { background:var(--surface); }\n') + len('  .band:not(.band-alt) .cell { background:var(--surface); }\n')
    out = home[:k] + '\n' + css + home[k:]
home = out
out = replace_between(home, '/* cards:js start', '/* cards:js end */', js)
if out is None:
    k = home.rindex('})();\n</script>')
    out = home[:k] + '\n' + js + home[k:]
home = out
# The scenes go before each card's <h3>, replacing any earlier copy.
home = re.sub(r'\s*<!-- cards:scene start -->[\s\S]*?<!-- cards:scene end -->\n', '\n', home)
cells = list(re.finditer(r'        <article class="cell">\n', home))
assert len(cells) == 6, len(cells)
for m, scene in reversed(list(zip(cells, scenes))):
    block = '          <!-- cards:scene start -->\n' + '\n'.join('    ' + l if l.strip() else l for l in scene.rstrip().split('\n')) + '\n          <!-- cards:scene end -->\n'
    home = home[:m.end()] + block + home[m.end():]
home_path.write_text(home)
print('built concepts/cards/index.html and the six scenes in public/index.html')
